import {api,bootstrap} from "./api.js";import {renderGraph} from "./graph-view.js";
type GraphPage={nodes:any[];edges:any[];next_cursor:string|null};type Capabilities={operations:boolean;graph_revision?:number;config_revision?:number};
let graphCursor:string|null=null,entityCursor:string|null=null,researchCursor:string|null=null,sourcesCursor:string|null=null,researchSection="insights",capabilities:Capabilities={operations:false},lastPreview:any,lastPayload:Record<string,unknown>={};
const $=<T extends Element>(selector:string)=>document.querySelector(selector) as T;
async function start(){await bootstrap();capabilities=await api<Capabilities>("/api/capabilities");const op=$<HTMLButtonElement>('button[data-view="operations"]');if(capabilities.operations)op.hidden=false;bindNavigation();bindForms();await showOverview();$("#status").textContent=capabilities.operations?"Operations enabled":"Read-only";}
function bindNavigation(){for(const button of document.querySelectorAll<HTMLButtonElement>("nav button"))button.addEventListener("click",()=>{for(const panel of document.querySelectorAll<HTMLElement>("[data-panel]"))panel.hidden=panel.id!==button.dataset.view;for(const item of document.querySelectorAll("nav button"))item.removeAttribute("aria-current");button.setAttribute("aria-current","page");if(button.dataset.view==="memory")void loadMemory();if(button.dataset.view==="intelligence")void loadIntelligence();if(button.dataset.view==="graph")void loadGraph(true);if(button.dataset.view==="sources"){sourcesCursor=null;void loadSources()}if(button.dataset.view==="trust")void loadTrust()});}
function bindForms(){$<HTMLFormElement>("#memory-form").addEventListener("submit",event=>{event.preventDefault();void loadMemory()});$<HTMLFormElement>("#intelligence-form").addEventListener("submit",event=>{event.preventDefault();void loadIntelligence()});$<HTMLFormElement>("#graph-filters").addEventListener("submit",event=>{event.preventDefault();void loadGraph(true)});$("#load-more").addEventListener("click",()=>void loadGraph(false));$<HTMLFormElement>("#entity-form").addEventListener("submit",event=>{event.preventDefault();entityCursor=null;void loadEntity()});$("#entity-next").addEventListener("click",()=>void loadEntity());for(const button of document.querySelectorAll<HTMLButtonElement>("[data-research]"))button.addEventListener("click",()=>{researchSection=button.dataset.research??"insights";researchCursor=null;void loadResearch()});$("#research-next").addEventListener("click",()=>void loadResearch());$("#sources-next").addEventListener("click",()=>void loadSources());$<HTMLFormElement>("#operation-form").addEventListener("submit",event=>{event.preventDefault();void previewOperation()});$("#confirm-operation").addEventListener("click",()=>void confirmOperation());}
async function showOverview(){const value=await api<any>("/api/overview");$("#overview-cards").innerHTML=["nodes","edges","observations","graph_revision"].map(key=>`<article class="card"><span>${key.replace("_"," ")}</span><strong>${Number(value[key]??0).toLocaleString()}</strong></article>`).join("");}
async function loadMemory(){const form=new FormData($<HTMLFormElement>("#memory-form")),section=String(form.get("section")??"today"),limit=Number(form.get("limit")??20),subject=String(form.get("subject")??"").trim();const result:any=await api("/api/memory",{section,limit,...(subject?{subject}:{})});$("#memory-result").textContent=JSON.stringify(result,null,2);}
async function loadIntelligence(){const form=new FormData($<HTMLFormElement>("#intelligence-form")),view=String(form.get("view")??"provenance"),value=String(form.get("value")??"").trim(),limit=Number(form.get("limit")??20),payload:any={view,limit};if(view==="provenance")payload.claim_id=value;if(view==="retrieval")payload.query=value;const result:any=await api("/api/intelligence",payload);$("#intelligence-result").textContent=JSON.stringify(result,null,2);}
async function loadGraph(reset:boolean){if(reset)graphCursor=null;const form=new FormData($<HTMLFormElement>("#graph-filters")),text=(name:string)=>String(form.get(name)??"").trim(),confidence=Number(form.get("confidence")??0);const filters:any={confidence_min:confidence};if(text("nodeType"))filters.node_types=[text("nodeType")];if(text("source"))filters.sources=[text("source")];if(text("community"))filters.community_id=text("community");if(text("validFrom"))filters.valid_from=Date.parse(`${text("validFrom")}T00:00:00.000Z`);if(text("validTo"))filters.valid_to=Date.parse(`${text("validTo")}T23:59:59.999Z`);const page=await api<GraphPage>("/api/graph",{kind:"graph",cursor:graphCursor??undefined,max_nodes:5000,max_edges:20000,filters});graphCursor=page.next_cursor;renderGraph($<HTMLElement>("#graph-canvas"),page);$<HTMLButtonElement>("#load-more").disabled=!graphCursor;}
async function loadEntity(){const form=new FormData($<HTMLFormElement>("#entity-form")),id=String(form.get("id")??""),section=String(form.get("section")??"evidence");const result:any=await api("/api/entity",{kind:"entity",id,section,cursor:entityCursor??undefined});entityCursor=result.next_cursor??null;$("#entity-result").textContent=JSON.stringify(result,null,2);$<HTMLButtonElement>("#entity-next").disabled=!entityCursor;}
async function loadResearch(){const result:any=await api("/api/research",{kind:"research",section:researchSection,cursor:researchCursor??undefined});researchCursor=result.next_cursor??null;$("#research-result").textContent=JSON.stringify(result,null,2);$<HTMLButtonElement>("#research-next").disabled=!researchCursor;}
async function loadSources(){const result:any=await api("/api/sources",{kind:"sources",cursor:sourcesCursor??undefined});sourcesCursor=result.next_cursor??null;$("#sources-result").textContent=JSON.stringify(result,null,2);$<HTMLButtonElement>("#sources-next").disabled=!sourcesCursor;}
async function loadTrust(){const result:any=await api("/api/trust");$("#trust-result").textContent=JSON.stringify(result,null,2);}
function operationPayload(operation:string,form:FormData){const target=String(form.get("target")??"").trim(),amount=Number(form.get("amount"));if(operation==="source_trust")return{source:target,weight:amount};if(operation==="restore")return{artifact_id:target};if(operation==="orphan_cleanup"||operation==="weight_recompute")return Number.isSafeInteger(amount)&&amount>0?{limit:amount}:{};return{};}
async function previewOperation(){const form=new FormData($<HTMLFormElement>("#operation-form")),operation=String(form.get("operation"));capabilities=await api<Capabilities>("/api/capabilities");lastPayload=operationPayload(operation,form);const request:any={operation,phase:"preview",graph_revision:capabilities.graph_revision??0,payload:lastPayload};if(operation==="source_trust")request.config_revision=capabilities.config_revision??0;lastPreview=await api("/api/operations/preview",request);$("#operation-result").textContent=JSON.stringify(lastPreview,null,2);$<HTMLButtonElement>("#confirm-operation").disabled=false;}
async function confirmOperation(){if(!lastPreview)return;const request:any={operation:lastPreview.operation,phase:"confirm",preview_token:lastPreview.preview_token,payload_hash:lastPreview.payload_hash,graph_revision:lastPreview.graph_revision,payload:lastPayload};if(lastPreview.operation==="source_trust")request.config_revision=lastPreview.config_revision;const result=await api("/api/operations/confirm",request);$("#operation-result").textContent=JSON.stringify(result,null,2);lastPreview=undefined;lastPayload={};$<HTMLButtonElement>("#confirm-operation").disabled=true;capabilities=await api<Capabilities>("/api/capabilities");await showOverview();}
start().catch(()=>{$("#status").textContent="Inspector unavailable"});
