import type { DatabaseSyncInstance } from "@photostructure/sqlite";
import { createHash, randomBytes as systemRandomBytes } from "node:crypto";
import type { OperationAffectedCounts, OrphanCleanupConfirmRequest, OrphanCleanupConfirmResult, OrphanCleanupPreviewRequest, OrphanCleanupPreviewResult, WeightRecomputeConfirmRequest, WeightRecomputeConfirmResult, WeightRecomputePreviewRequest, WeightRecomputePreviewResult } from "./types.js";

interface Store { db:DatabaseSyncInstance; graphRevision():number; bumpGraphRevision():void; }
type PreviewRequest=OrphanCleanupPreviewRequest|WeightRecomputePreviewRequest; type ConfirmRequest=OrphanCleanupConfirmRequest|WeightRecomputeConfirmRequest;
type Pending={operation:"orphan_cleanup"|"weight_recompute";hash:string;graph:number;limit:number;ids:string[];expires:number;affected:OperationAffectedCounts};
export class MaintenanceService {
  private readonly now:()=>number; private readonly randomBytes:(size:number)=>Buffer; private readonly pending=new Map<string,Pending>();
  constructor(private readonly options:{store:Store;now?:()=>number;randomBytes?:(size:number)=>Buffer;ttlMs?:number}){this.now=options.now??Date.now;this.randomBytes=options.randomBytes??systemRandomBytes;}
  preview(input:PreviewRequest):OrphanCleanupPreviewResult|WeightRecomputePreviewResult{
    const graph=this.options.store.graphRevision();if(input.graph_revision!==graph)throw new Error("stale_preview");const limit=Math.min(1000,Math.max(1,Math.trunc(input.payload.limit??100)));
    const projection=input.operation==="orphan_cleanup"?this.orphans(limit):this.weights(limit),hash=sha({operation:input.operation,graph,limit,ids:projection.ids}),token=secret(this.randomBytes);
    this.pending.set(token,{operation:input.operation,hash,graph,limit,ids:projection.ids,expires:this.now()+300000,affected:projection.affected});
    return {operation:input.operation,phase:"preview",preview_token:token,payload_hash:hash,graph_revision:graph,affected:projection.affected,truncated:projection.truncated} as OrphanCleanupPreviewResult|WeightRecomputePreviewResult;
  }
  confirm(input:ConfirmRequest):OrphanCleanupConfirmResult|WeightRecomputeConfirmResult{
    const pending=this.pending.get(input.preview_token);this.pending.delete(input.preview_token);if(!pending||pending.expires<this.now()||pending.operation!==input.operation||pending.hash!==input.payload_hash)throw new Error("invalid_preview");
    const db=this.options.store.db;db.exec("BEGIN IMMEDIATE");try{if(this.options.store.graphRevision()!==pending.graph||input.graph_revision!==pending.graph)throw new Error("stale_preview");const fresh=input.operation==="orphan_cleanup"?this.orphans(pending.limit):this.weights(pending.limit);if(sha({operation:input.operation,graph:pending.graph,limit:pending.limit,ids:fresh.ids})!==pending.hash)throw new Error("stale_preview");
      if(input.operation==="orphan_cleanup"){for(const id of pending.ids){db.prepare("DELETE FROM kg_observations WHERE source_entity_id=?").run(id);db.prepare("UPDATE kg_nodes SET deleted_at=?,updated_at=? WHERE id=? AND deleted_at IS NULL").run(this.now(),this.now(),id);}}
      else {const changedAt=Math.trunc(this.now());for(const key of pending.ids){const split=key.indexOf("\0"),kind=key.slice(0,split),id=key.slice(split+1);if(kind==="edge")db.prepare("UPDATE kg_edges SET weight=COALESCE((SELECT MIN(1,COUNT(*)*AVG(confidence)/5) FROM kg_observations WHERE edge_id=kg_edges.id),0),updated_at=? WHERE id=? AND deleted_at IS NULL").run(changedAt,id);else if(kind==="node")db.prepare("UPDATE kg_nodes SET importance=COALESCE((SELECT MIN(1,COUNT(*)/5.0) FROM kg_observations WHERE source_entity_id=kg_nodes.id),0),updated_at=? WHERE id=? AND deleted_at IS NULL").run(changedAt,id);}}
      if(pending.ids.length)this.options.store.bumpGraphRevision();const audit=`audit:${secret(this.randomBytes).slice(0,32)}`;db.prepare("INSERT INTO kg_quality_audits(id,action,snapshot_version,snapshot,created_at) VALUES(?,?,1,?,?)").run(audit,input.operation,JSON.stringify({affected:pending.affected,count:pending.ids.length}),this.now());db.exec("COMMIT");return {operation:input.operation,phase:"confirm",confirmed:true,graph_revision:this.options.store.graphRevision(),audit_id:audit,affected:pending.affected} as OrphanCleanupConfirmResult|WeightRecomputeConfirmResult;
    }catch(error){db.exec("ROLLBACK");throw error;}
  }
  private orphans(limit:number){const rows=this.options.store.db.prepare("SELECT id FROM kg_nodes n WHERE deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM kg_edges e WHERE e.deleted_at IS NULL AND(e.source_id=n.id OR e.target_id=n.id)) ORDER BY id LIMIT ?").all(limit+1) as Array<{id:string}>;const ids=rows.slice(0,limit).map(r=>r.id);const obs=ids.length?Number((this.options.store.db.prepare(`SELECT COUNT(*) AS n FROM kg_observations WHERE source_entity_id IN (${ids.map(()=>'?').join(',')})`).get(...ids) as {n:number}).n):0;return{ids,affected:{nodes:ids.length,edges:0,observations:obs},truncated:rows.length>limit};}
  private weights(limit:number){const rows=this.options.store.db.prepare(`SELECT kind,id FROM (SELECT 'edge' AS kind,e.id AS id FROM kg_edges e WHERE e.deleted_at IS NULL AND ABS(e.weight-COALESCE((SELECT MIN(1,COUNT(*)*AVG(confidence)/5) FROM kg_observations WHERE edge_id=e.id),0))>0.000001 UNION ALL SELECT 'node' AS kind,n.id AS id FROM kg_nodes n WHERE n.deleted_at IS NULL AND ABS(n.importance-COALESCE((SELECT MIN(1,COUNT(*)/5.0) FROM kg_observations WHERE source_entity_id=n.id),0))>0.000001) ORDER BY kind,id LIMIT ?`).all(limit+1) as Array<{kind:"edge"|"node";id:string}>;const selected=rows.slice(0,limit),ids=selected.map(r=>`${r.kind}\0${r.id}`);return{ids,affected:{nodes:selected.filter(r=>r.kind==="node").length,edges:selected.filter(r=>r.kind==="edge").length,observations:0},truncated:rows.length>limit};}
}
function sha(v:unknown){return createHash("sha256").update(JSON.stringify(v)).digest("hex");}function secret(r:(n:number)=>Buffer){const v=r(32);if(!Buffer.isBuffer(v)||v.length!==32)throw new Error("entropy_unavailable");return v.toString("base64url");}
