import { createHash, randomUUID } from "node:crypto";
import type { DatabaseSyncInstance } from "@photostructure/sqlite";
import { normalizeScope } from "../scope.js";

export type EpisodeKind = "interaction"|"task"|"decision"|"experience"|"milestone"|"incident";
export type EpisodeStatus = "active"|"archived"|"superseded"|"deleted";
export interface Episode { id:string; scope:string; kind:EpisodeKind; title?:string; summary:string; participantEntityIds:string[]; sourceEventIds:string[]; sourceArtifactIds:string[]; eventStart?:number; eventEnd?:number; recordedAt:number; importance:number; confidence:number; status:EpisodeStatus; supersededBy?:string; }
const kinds = new Set<EpisodeKind>(["interaction","task","decision","experience","milestone","incident"]), hash=(value:string)=>createHash("sha256").update(value).digest("hex");
export class EpisodeRepository {
 constructor(private readonly db:DatabaseSyncInstance){}
 create(input:Omit<Episode,"id"|"recordedAt"|"status"|"participantEntityIds"|"sourceEventIds"|"sourceArtifactIds"> & { id?:string; participantEntityIds?:string[]; sourceEventIds:string[]; sourceArtifactIds?:string[]; recordedAt?:number; status?:EpisodeStatus }):Episode { const scope=normalizeScope(input.scope), ids=[...new Set(input.sourceEventIds)].slice(0,100), artifacts=[...new Set(input.sourceArtifactIds??[])].slice(0,100), participants=[...new Set(input.participantEntityIds??[])].slice(0,50), summary=input.summary.trim().slice(0,16000), now=input.recordedAt??Date.now(); if(!kinds.has(input.kind)||!summary||!ids.length||!Number.isFinite(input.importance)||input.importance<0||input.importance>1||!Number.isFinite(input.confidence)||input.confidence<0||input.confidence>1||input.eventStart!=null&&input.eventEnd!=null&&input.eventStart>input.eventEnd) throw new Error("invalid_episode"); const sourceHash=hash(JSON.stringify({ids,artifacts,summary,kind:input.kind})); const existing=this.db.prepare("SELECT id FROM mnemora_episodes WHERE scope=? AND content_hash=? AND deleted_at IS NULL").get(scope,sourceHash) as {id:string}|undefined; if(existing)return this.get(existing.id,scope)!; if(ids.some(id=>!this.db.prepare("SELECT 1 FROM mnemora_conversation_events WHERE id=? AND scope=? AND deleted_at IS NULL").get(id,scope))||artifacts.some(id=>!this.db.prepare("SELECT 1 FROM mnemora_artifacts WHERE id=? AND scope=? AND deleted_at IS NULL").get(id,scope)))throw new Error("invalid_episode_source"); const id=input.id??randomUUID(); this.db.exec("BEGIN IMMEDIATE"); try { this.db.prepare("INSERT OR IGNORE INTO kg_scopes(id,created_at,updated_at) VALUES(?,?,?)").run(scope,now,now); this.db.prepare("INSERT INTO mnemora_episodes(id,scope,kind,title,summary,content_hash,event_start,event_end,recorded_at,importance,confidence,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(id,scope,input.kind,input.title?.trim().slice(0,512)??null,summary,sourceHash,input.eventStart??null,input.eventEnd??null,now,input.importance,input.confidence,input.status??"active"); const e=this.db.prepare("INSERT INTO mnemora_episode_event_edges(episode_id,event_id,scope,ordinal) VALUES(?,?,?,?)");ids.forEach((value,i)=>e.run(id,value,scope,i));const a=this.db.prepare("INSERT INTO mnemora_episode_artifact_edges(episode_id,artifact_id,scope,ordinal) VALUES(?,?,?,?)");artifacts.forEach((value,i)=>a.run(id,value,scope,i));const p=this.db.prepare("INSERT INTO mnemora_episode_participants(episode_id,entity_id,scope) VALUES(?,?,?)");participants.forEach(value=>p.run(id,value,scope));this.db.exec("COMMIT");}catch(error){try{this.db.exec("ROLLBACK");}catch{}throw error}return this.get(id,scope)!; }
 get(id:string,scope:string):Episode|undefined {const row=this.db.prepare("SELECT * FROM mnemora_episodes WHERE id=? AND scope=? AND deleted_at IS NULL").get(id,normalizeScope(scope)) as Record<string,unknown>|undefined;if(!row)return;const ids=(sql:string,key:string)=>(this.db.prepare(sql).all(id,row.scope) as Array<Record<string,string>>).map(x=>x[key]);return {id:String(row.id),scope:String(row.scope),kind:row.kind as EpisodeKind,...(row.title?{title:String(row.title)}:{}),summary:String(row.summary),participantEntityIds:ids("SELECT entity_id FROM mnemora_episode_participants WHERE episode_id=? AND scope=?","entity_id"),sourceEventIds:ids("SELECT event_id FROM mnemora_episode_event_edges WHERE episode_id=? AND scope=? ORDER BY ordinal","event_id"),sourceArtifactIds:ids("SELECT artifact_id FROM mnemora_episode_artifact_edges WHERE episode_id=? AND scope=? ORDER BY ordinal","artifact_id"),...(row.event_start?{eventStart:Number(row.event_start)}:{}),...(row.event_end?{eventEnd:Number(row.event_end)}:{}),recordedAt:Number(row.recorded_at),importance:Number(row.importance),confidence:Number(row.confidence),status:row.status as EpisodeStatus,...(row.superseded_by?{supersededBy:String(row.superseded_by)}:{})};}
 search(scope:string,query:string,limit=20):Episode[]{const q=query.trim().slice(0,512);if(!q)return[];const rows=this.db.prepare("SELECT id FROM mnemora_episodes WHERE scope=? AND status='active' AND deleted_at IS NULL AND (instr(summary,?)>0 OR instr(COALESCE(title,''),?)>0) ORDER BY importance DESC,recorded_at DESC LIMIT ?").all(normalizeScope(scope),q,q,Math.min(100,Math.max(1,limit))) as Array<{id:string}>;return rows.flatMap(row=>{const value=this.get(row.id,scope);return value?[value]:[]});}
 transition(id:string,scope:string,status:Exclude<EpisodeStatus,"active">,supersededBy?:string):Episode {const current=this.get(id,scope);if(!current||status==="superseded"&&!supersededBy)throw new Error("invalid_episode_transition");if(supersededBy&&!this.get(supersededBy,scope))throw new Error("invalid_episode_transition");const now=Date.now();this.db.prepare("UPDATE mnemora_episodes SET status=?,superseded_by=?,archived_at=?,deleted_at=? WHERE id=? AND scope=?").run(status,supersededBy??null,status==="archived"?now:null,status==="deleted"?now:null,id,normalizeScope(scope));return {...current,status,...(supersededBy?{supersededBy}:{})};}
}
